spring:
  application:
    name: FlowerShop
    version: '@project.version@'

  datasource:
    url: jdbc:mysql://localhost:3306/flower_shop_web
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: flower_shop_web
    backup-path: C:\database_backup\flowershop\
    install-path: "C:\\Program Files\\MySQL\\MySQL Server 5.6\\bin\\"

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      repositories:
        enabled: false

  mail:
    host: smtp-mail.outlook.com
    username: # 请配置真实的邮箱
    password: # smtp密码
    port: 587

server:
  port: 8080
